//This file is automatically generated by generator.lua from https://github.com/gucio321/cimmarkdown
//based on TextEditor.h file version XXX from ImGuiColorTextEdit https://github.com/BalazsJako/ImGuiColorTextEdit

#include "./ImGuiTextEdit/TextEditor.h"
#include "cimgui_textedit.h"


