//This file is automatically generated by generator.lua from https://github.com/gucio321/cimmarkdown
//based on TextEditor.h file version XXX from ImGuiColorTextEdit https://github.com/BalazsJako/ImGuiColorTextEdit
#ifndef CIMGUI_TEXTEDIT_INCLUDED
#define CIMGUI_TEXTEDIT_INCLUDED

#define NUMHEADINGS 3 // this is because struct field in imgui_markdown is static so we can't wrap it to C

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#include <time.h>
typedef struct tm tm;


#else

#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS



#endif //CIMMARKDOWN_INCLUDED




